export const NATIONALITIES = {
  AU: 'AU',
  BR: 'BR',
  CA: 'CA',
  CH: 'CH',
  DE: 'DE',
  DK: 'DK',
  ES: 'ES',
  FI: 'FI',
  FR: 'FR',
  GB: 'GB',
  IE: 'IE',
  IN: 'IN',
  IR: 'IR',
  MX: 'MX',
  NO: 'NO',
  NL: 'NL',
  NZ: 'NZ',
  RS: 'RS',
  TR: 'TR',
  UA: 'UA',
  US: 'US',
};

export const NATIONALITIES_HUMAN_NAME = {
  [NATIONALITIES.AU]: 'Australian',
  [NATIONALITIES.BR]: 'Brazilian',
  [NATIONALITIES.CA]: 'Canadian',
  [NATIONALITIES.CH]: 'Chinese',
  [NATIONALITIES.DE]: 'German',
  [NATIONALITIES.DK]: 'Danish',
  [NATIONALITIES.ES]: 'Spanish',
  [NATIONALITIES.FI]: 'Finnish',
  [NATIONALITIES.FR]: 'French',
  [NATIONALITIES.GB]: 'British',
  [NATIONALITIES.IE]: 'Irish',
  [NATIONALITIES.IN]: 'Indian',
  [NATIONALITIES.IR]: 'Iranian',
  [NATIONALITIES.MX]: 'Mexican',
  [NATIONALITIES.NO]: 'Norwegian',
  [NATIONALITIES.NL]: 'Dutch',
  [NATIONALITIES.NZ]: 'New Zealand',
  [NATIONALITIES.RS]: 'Serbian',
  [NATIONALITIES.TR]: 'Turkish',
  [NATIONALITIES.UA]: 'Ukrainian',
  [NATIONALITIES.US]: 'American',
};
